// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBuqCY5iKdFuXS5npOp-j-l-gxHudYrKYs',
    appId: '1:195092382674:web:6b0e72c8e2e5f8a73a3e0b',
    messagingSenderId: '195092382674',
    projectId: 'walletapp-ece89',
    authDomain: 'walletapp-ece89.firebaseapp.com',
    storageBucket: 'walletapp-ece89.firebasestorage.app',
    measurementId: 'G-3D1F6DQ4BF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAI1UmlIB4EHWhy-eEB1BdCMsRILeEk6l0',
    appId: '1:195092382674:android:dbac2b1620ade1b93a3e0b',
    messagingSenderId: '195092382674',
    projectId: 'walletapp-ece89',
    storageBucket: 'walletapp-ece89.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJxSF3oJBT98XRSqhhzsTrbt1Qygv3Xak',
    appId: '1:195092382674:ios:a869e4942b428e283a3e0b',
    messagingSenderId: '195092382674',
    projectId: 'walletapp-ece89',
    storageBucket: 'walletapp-ece89.firebasestorage.app',
    androidClientId: '195092382674-pnj540auubdc5kqe8hhhf00t8rf4ejqs.apps.googleusercontent.com',
    iosClientId: '195092382674-m5t5v6dqta3tf72vrbmtumre0lq6hnfr.apps.googleusercontent.com',
    iosBundleId: 'com.bulut.wallet',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBJxSF3oJBT98XRSqhhzsTrbt1Qygv3Xak',
    appId: '1:195092382674:ios:8b5a4aefe90706f33a3e0b',
    messagingSenderId: '195092382674',
    projectId: 'walletapp-ece89',
    storageBucket: 'walletapp-ece89.firebasestorage.app',
    androidClientId: '195092382674-pnj540auubdc5kqe8hhhf00t8rf4ejqs.apps.googleusercontent.com',
    iosClientId: '195092382674-bjrfeii11bo447tjp3vmouv4rskndisn.apps.googleusercontent.com',
    iosBundleId: 'com.example.money',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBuqCY5iKdFuXS5npOp-j-l-gxHudYrKYs',
    appId: '1:195092382674:web:8d3cff1e5ba8666d3a3e0b',
    messagingSenderId: '195092382674',
    projectId: 'walletapp-ece89',
    authDomain: 'walletapp-ece89.firebaseapp.com',
    storageBucket: 'walletapp-ece89.firebasestorage.app',
    measurementId: 'G-0VDQBF1N3J',
  );

}