// Mocks generated by Mockito 5.4.4 from annotations
// in money/test/services/auth/auth_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:money/models/security/security_models.dart' as _i2;
import 'package:money/services/auth/biometric_service.dart' as _i5;
import 'package:money/services/auth/pin_service.dart' as _i3;
import 'package:money/services/auth/secure_storage_service.dart' as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeAuthResult_0 extends _i1.SmartFake implements _i2.AuthResult {
  _FakeAuthResult_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [PINService].
///
/// See the documentation for Mockito's code generation for more information.
class MockPINService extends _i1.Mock implements _i3.PINService {
  MockPINService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<void> initialize() => (super.noSuchMethod(
        Invocation.method(
          #initialize,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<_i2.AuthResult> setupPIN(String? pin) => (super.noSuchMethod(
        Invocation.method(
          #setupPIN,
          [pin],
        ),
        returnValue: _i4.Future<_i2.AuthResult>.value(_FakeAuthResult_0(
          this,
          Invocation.method(
            #setupPIN,
            [pin],
          ),
        )),
      ) as _i4.Future<_i2.AuthResult>);

  @override
  _i4.Future<_i2.AuthResult> verifyPIN(String? pin) => (super.noSuchMethod(
        Invocation.method(
          #verifyPIN,
          [pin],
        ),
        returnValue: _i4.Future<_i2.AuthResult>.value(_FakeAuthResult_0(
          this,
          Invocation.method(
            #verifyPIN,
            [pin],
          ),
        )),
      ) as _i4.Future<_i2.AuthResult>);

  @override
  _i4.Future<_i2.AuthResult> changePIN(
    String? oldPin,
    String? newPin,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #changePIN,
          [
            oldPin,
            newPin,
          ],
        ),
        returnValue: _i4.Future<_i2.AuthResult>.value(_FakeAuthResult_0(
          this,
          Invocation.method(
            #changePIN,
            [
              oldPin,
              newPin,
            ],
          ),
        )),
      ) as _i4.Future<_i2.AuthResult>);

  @override
  _i4.Future<_i2.AuthResult> resetPIN() => (super.noSuchMethod(
        Invocation.method(
          #resetPIN,
          [],
        ),
        returnValue: _i4.Future<_i2.AuthResult>.value(_FakeAuthResult_0(
          this,
          Invocation.method(
            #resetPIN,
            [],
          ),
        )),
      ) as _i4.Future<_i2.AuthResult>);

  @override
  _i4.Future<int> getFailedAttempts() => (super.noSuchMethod(
        Invocation.method(
          #getFailedAttempts,
          [],
        ),
        returnValue: _i4.Future<int>.value(0),
      ) as _i4.Future<int>);

  @override
  _i4.Future<bool> isLocked() => (super.noSuchMethod(
        Invocation.method(
          #isLocked,
          [],
        ),
        returnValue: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);

  @override
  _i4.Future<Duration?> getRemainingLockoutTime() => (super.noSuchMethod(
        Invocation.method(
          #getRemainingLockoutTime,
          [],
        ),
        returnValue: _i4.Future<Duration?>.value(),
      ) as _i4.Future<Duration?>);

  @override
  _i4.Future<bool> isPINSet() => (super.noSuchMethod(
        Invocation.method(
          #isPINSet,
          [],
        ),
        returnValue: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);

  @override
  int checkPINStrength(String? pin) => (super.noSuchMethod(
        Invocation.method(
          #checkPINStrength,
          [pin],
        ),
        returnValue: 0,
      ) as int);

  @override
  _i4.Future<bool> clearAllPINData() => (super.noSuchMethod(
        Invocation.method(
          #clearAllPINData,
          [],
        ),
        returnValue: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);

  @override
  void resetForTesting() => super.noSuchMethod(
        Invocation.method(
          #resetForTesting,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [BiometricService].
///
/// See the documentation for Mockito's code generation for more information.
class MockBiometricService extends _i1.Mock implements _i5.BiometricService {
  MockBiometricService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<bool> isBiometricAvailable() => (super.noSuchMethod(
        Invocation.method(
          #isBiometricAvailable,
          [],
        ),
        returnValue: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);

  @override
  _i4.Future<List<_i2.BiometricType>> getAvailableBiometrics() =>
      (super.noSuchMethod(
        Invocation.method(
          #getAvailableBiometrics,
          [],
        ),
        returnValue:
            _i4.Future<List<_i2.BiometricType>>.value(<_i2.BiometricType>[]),
      ) as _i4.Future<List<_i2.BiometricType>>);

  @override
  _i4.Future<_i2.AuthResult> authenticate({
    String? localizedFallbackTitle,
    String? cancelButtonText,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #authenticate,
          [],
          {
            #localizedFallbackTitle: localizedFallbackTitle,
            #cancelButtonText: cancelButtonText,
          },
        ),
        returnValue: _i4.Future<_i2.AuthResult>.value(_FakeAuthResult_0(
          this,
          Invocation.method(
            #authenticate,
            [],
            {
              #localizedFallbackTitle: localizedFallbackTitle,
              #cancelButtonText: cancelButtonText,
            },
          ),
        )),
      ) as _i4.Future<_i2.AuthResult>);

  @override
  _i4.Future<bool> enrollBiometric() => (super.noSuchMethod(
        Invocation.method(
          #enrollBiometric,
          [],
        ),
        returnValue: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);

  @override
  _i4.Future<void> disableBiometric() => (super.noSuchMethod(
        Invocation.method(
          #disableBiometric,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<bool> isDeviceSecure() => (super.noSuchMethod(
        Invocation.method(
          #isDeviceSecure,
          [],
        ),
        returnValue: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);

  @override
  _i4.Future<bool> canCheckBiometrics() => (super.noSuchMethod(
        Invocation.method(
          #canCheckBiometrics,
          [],
        ),
        returnValue: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);
}

/// A class which mocks [AuthSecureStorageService].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthSecureStorageService extends _i1.Mock
    implements _i6.AuthSecureStorageService {
  MockAuthSecureStorageService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<void> initialize() => (super.noSuchMethod(
        Invocation.method(
          #initialize,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<bool> isSecureStorageAvailable() => (super.noSuchMethod(
        Invocation.method(
          #isSecureStorageAvailable,
          [],
        ),
        returnValue: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);

  @override
  _i4.Future<bool> storePIN(String? pin) => (super.noSuchMethod(
        Invocation.method(
          #storePIN,
          [pin],
        ),
        returnValue: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);

  @override
  _i4.Future<bool> verifyPIN(String? pin) => (super.noSuchMethod(
        Invocation.method(
          #verifyPIN,
          [pin],
        ),
        returnValue: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);

  @override
  _i4.Future<bool> isPINSet() => (super.noSuchMethod(
        Invocation.method(
          #isPINSet,
          [],
        ),
        returnValue: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);

  @override
  _i4.Future<bool> removePIN() => (super.noSuchMethod(
        Invocation.method(
          #removePIN,
          [],
        ),
        returnValue: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);

  @override
  _i4.Future<bool> storeBiometricConfig(
    bool? isEnabled,
    String? biometricType,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #storeBiometricConfig,
          [
            isEnabled,
            biometricType,
          ],
        ),
        returnValue: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);

  @override
  _i4.Future<Map<String, dynamic>?> getBiometricConfig() => (super.noSuchMethod(
        Invocation.method(
          #getBiometricConfig,
          [],
        ),
        returnValue: _i4.Future<Map<String, dynamic>?>.value(),
      ) as _i4.Future<Map<String, dynamic>?>);

  @override
  _i4.Future<bool> storeFailedAttempts(int? count) => (super.noSuchMethod(
        Invocation.method(
          #storeFailedAttempts,
          [count],
        ),
        returnValue: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);

  @override
  _i4.Future<int> getFailedAttempts() => (super.noSuchMethod(
        Invocation.method(
          #getFailedAttempts,
          [],
        ),
        returnValue: _i4.Future<int>.value(0),
      ) as _i4.Future<int>);

  @override
  _i4.Future<bool> storeLockoutTime(DateTime? lockoutTime) =>
      (super.noSuchMethod(
        Invocation.method(
          #storeLockoutTime,
          [lockoutTime],
        ),
        returnValue: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);

  @override
  _i4.Future<DateTime?> getLockoutTime() => (super.noSuchMethod(
        Invocation.method(
          #getLockoutTime,
          [],
        ),
        returnValue: _i4.Future<DateTime?>.value(),
      ) as _i4.Future<DateTime?>);

  @override
  _i4.Future<bool> clearLockout() => (super.noSuchMethod(
        Invocation.method(
          #clearLockout,
          [],
        ),
        returnValue: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);

  @override
  _i4.Future<bool> storeSecurityConfig(_i2.SecurityConfig? config) =>
      (super.noSuchMethod(
        Invocation.method(
          #storeSecurityConfig,
          [config],
        ),
        returnValue: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);

  @override
  _i4.Future<_i2.SecurityConfig?> getSecurityConfig() => (super.noSuchMethod(
        Invocation.method(
          #getSecurityConfig,
          [],
        ),
        returnValue: _i4.Future<_i2.SecurityConfig?>.value(),
      ) as _i4.Future<_i2.SecurityConfig?>);

  @override
  _i4.Future<bool> storeAuthState(_i2.AuthState? authState) =>
      (super.noSuchMethod(
        Invocation.method(
          #storeAuthState,
          [authState],
        ),
        returnValue: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);

  @override
  _i4.Future<_i2.AuthState?> getAuthState() => (super.noSuchMethod(
        Invocation.method(
          #getAuthState,
          [],
        ),
        returnValue: _i4.Future<_i2.AuthState?>.value(),
      ) as _i4.Future<_i2.AuthState?>);

  @override
  _i4.Future<bool> clearAuthState() => (super.noSuchMethod(
        Invocation.method(
          #clearAuthState,
          [],
        ),
        returnValue: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);

  @override
  _i4.Future<bool> storeSessionData(_i2.SessionData? sessionData) =>
      (super.noSuchMethod(
        Invocation.method(
          #storeSessionData,
          [sessionData],
        ),
        returnValue: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);

  @override
  _i4.Future<_i2.SessionData?> getSessionData() => (super.noSuchMethod(
        Invocation.method(
          #getSessionData,
          [],
        ),
        returnValue: _i4.Future<_i2.SessionData?>.value(),
      ) as _i4.Future<_i2.SessionData?>);

  @override
  _i4.Future<bool> clearSessionData() => (super.noSuchMethod(
        Invocation.method(
          #clearSessionData,
          [],
        ),
        returnValue: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);

  @override
  _i4.Future<bool> storeSessionState(dynamic sessionState) =>
      (super.noSuchMethod(
        Invocation.method(
          #storeSessionState,
          [sessionState],
        ),
        returnValue: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);

  @override
  _i4.Future<dynamic> getSessionState() => (super.noSuchMethod(
        Invocation.method(
          #getSessionState,
          [],
        ),
        returnValue: _i4.Future<dynamic>.value(),
      ) as _i4.Future<dynamic>);

  @override
  _i4.Future<bool> clearSessionState() => (super.noSuchMethod(
        Invocation.method(
          #clearSessionState,
          [],
        ),
        returnValue: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);

  @override
  _i4.Future<bool> storeDeviceId(String? deviceId) => (super.noSuchMethod(
        Invocation.method(
          #storeDeviceId,
          [deviceId],
        ),
        returnValue: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);

  @override
  _i4.Future<String?> getDeviceId() => (super.noSuchMethod(
        Invocation.method(
          #getDeviceId,
          [],
        ),
        returnValue: _i4.Future<String?>.value(),
      ) as _i4.Future<String?>);

  @override
  _i4.Future<bool> storeSecurityQuestions(String? questionsJson) =>
      (super.noSuchMethod(
        Invocation.method(
          #storeSecurityQuestions,
          [questionsJson],
        ),
        returnValue: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);

  @override
  _i4.Future<String?> getSecurityQuestions() => (super.noSuchMethod(
        Invocation.method(
          #getSecurityQuestions,
          [],
        ),
        returnValue: _i4.Future<String?>.value(),
      ) as _i4.Future<String?>);

  @override
  _i4.Future<bool> areSecurityQuestionsSet() => (super.noSuchMethod(
        Invocation.method(
          #areSecurityQuestionsSet,
          [],
        ),
        returnValue: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);

  @override
  _i4.Future<bool> clearSecurityQuestions() => (super.noSuchMethod(
        Invocation.method(
          #clearSecurityQuestions,
          [],
        ),
        returnValue: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);

  @override
  _i4.Future<bool> storePINRecoveryState(String? stateJson) =>
      (super.noSuchMethod(
        Invocation.method(
          #storePINRecoveryState,
          [stateJson],
        ),
        returnValue: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);

  @override
  _i4.Future<String?> getPINRecoveryState() => (super.noSuchMethod(
        Invocation.method(
          #getPINRecoveryState,
          [],
        ),
        returnValue: _i4.Future<String?>.value(),
      ) as _i4.Future<String?>);

  @override
  _i4.Future<bool> clearPINRecoveryState() => (super.noSuchMethod(
        Invocation.method(
          #clearPINRecoveryState,
          [],
        ),
        returnValue: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);

  @override
  _i4.Future<bool> clearAllAuthData() => (super.noSuchMethod(
        Invocation.method(
          #clearAllAuthData,
          [],
        ),
        returnValue: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);

  @override
  _i4.Future<String?> getEncryptionKey() => (super.noSuchMethod(
        Invocation.method(
          #getEncryptionKey,
          [],
        ),
        returnValue: _i4.Future<String?>.value(),
      ) as _i4.Future<String?>);

  @override
  _i4.Future<bool> hasDeviceChanged(String? currentDeviceId) =>
      (super.noSuchMethod(
        Invocation.method(
          #hasDeviceChanged,
          [currentDeviceId],
        ),
        returnValue: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);

  @override
  void resetForTesting() => super.noSuchMethod(
        Invocation.method(
          #resetForTesting,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i4.Future<dynamic> read(String? key) => (super.noSuchMethod(
        Invocation.method(
          #read,
          [key],
        ),
        returnValue: _i4.Future<dynamic>.value(),
      ) as _i4.Future<dynamic>);

  @override
  _i4.Future<bool> write(
    String? key,
    dynamic value,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #write,
          [
            key,
            value,
          ],
        ),
        returnValue: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);

  @override
  _i4.Future<bool> delete(String? key) => (super.noSuchMethod(
        Invocation.method(
          #delete,
          [key],
        ),
        returnValue: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);
}
